version: '3'
services:
  django-app:
    container_name: django
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    entrypoint: ["tail", "-f", "/dev/null"]

  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword

