version: '3'
services:
  django-app:
    container_name: django
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: mysql
    image: mysql:8.0
    env_file:
      - ./backend/dev-env.env

