# Generated by Django 4.2.5 on 2023-10-24 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TVMazeShow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tv_maze_id", models.PositiveIntegerField(unique=True)),
                ("url", models.URLField(null=True)),
                ("name", models.CharField(max_length=255, null=True)),
                ("type", models.CharField(max_length=255, null=True)),
                ("language", models.CharField(max_length=255, null=True)),
                ("genres", models.JSONField(null=True)),
                ("status", models.CharField(max_length=255, null=True)),
                ("runtime", models.PositiveIntegerField(null=True)),
                ("averageRuntime", models.PositiveIntegerField(null=True)),
                ("premiered", models.DateField(null=True)),
                ("ended", models.DateField(null=True)),
                ("officialSite", models.URLField(null=True)),
                ("schedule", models.JSONField(null=True)),
                ("rating", models.JSONField(null=True)),
                ("weight", models.PositiveIntegerField(null=True)),
                ("network", models.JSONField(null=True)),
                ("webChannel", models.JSONField(null=True)),
                ("dvdCountry", models.CharField(max_length=255, null=True)),
                ("externals", models.JSONField(null=True)),
                ("image", models.JSONField(null=True)),
                ("summary", models.TextField(null=True)),
                ("updated", models.CharField(max_length=255, null=True)),
                ("_links", models.JSONField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
