# Generated by Django 4.2.5 on 2023-10-24 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(max_length=255)),
                ("timezone", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
            },
        ),
        migrations.CreateModel(
            name="Network",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("official_site", models.URLField(null=True)),
                (
                    "country",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="networks",
                        to="core.country",
                    ),
                ),
            ],
            options={
                "verbose_name": "Network",
                "verbose_name_plural": "Networks",
            },
        ),
        migrations.CreateModel(
            name="ShowStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "ShowStatus",
                "verbose_name_plural": "ShowStatuses",
            },
        ),
        migrations.CreateModel(
            name="Show",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("name", models.CharField(max_length=255)),
                ("type", models.CharField(max_length=255)),
                ("language", models.CharField(max_length=255)),
                ("runtime", models.PositiveIntegerField(null=True)),
                ("averageRuntime", models.PositiveIntegerField(null=True)),
                ("premiered", models.DateField(null=True)),
                ("ended", models.DateField(null=True)),
                ("officialSite", models.URLField(null=True)),
                ("schedule_time", models.TimeField(null=True)),
                ("schedule_days", models.JSONField(null=True)),
                ("rating", models.FloatField(null=True)),
                ("weight", models.PositiveIntegerField(null=True)),
                ("webChannel", models.JSONField(null=True)),
                ("dvdCountry", models.CharField(max_length=255, null=True)),
                ("externals", models.JSONField(null=True)),
                ("image", models.JSONField(null=True)),
                ("summary", models.TextField(null=True)),
                (
                    "network",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shows",
                        to="core.network",
                    ),
                ),
                (
                    "status",
                    models.ManyToManyField(related_name="shows", to="core.showstatus"),
                ),
            ],
            options={
                "verbose_name": "Show",
                "verbose_name_plural": "Shows",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "show",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="genres",
                        to="core.show",
                    ),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
            },
        ),
    ]
